### ISSUE TITLE
Next step indicator moves when window size changes

### ISSUE THREAD

**Issue by blakeelias** [Pandemic-Game/pandemic-game#107]
Can we get this to always stay aligned with the current time step, no matter how you change your window size?

If you make your window a bit narrower or wider on a current turn, you'll see that it shifts (at least in Chrome).
Once you advance to the next turn, it does re-align itself to that time step. But *within* a turn, it can get misaligned.

The rest of the game doesn't shift - it stays at a fixed position. We should make the turn highlighting work the same way.

**Comment by blakeelias** [comment]
Exaggerated version of this issue on my large screen:

![Screenshot from 2020-12-16 12-09-06](https://user-images.githubusercontent.com/393923/102381669-8215a400-3f97-11eb-8e0f-ad0c140e2141.png)

**Comment by blakeelias** [comment]
By the way this is probably the most urgent issue we have right now before Yaneer can send it to his people.
Other than that, everything's good enough to go ahead. Even with this as it is, I think it'd probably be fine -- it's just a bit confusing and I think would be quick enough to fix that it's worth doing. As soon as it's done Yaneer wants to send it to people.

**Comment by CMorenoStokoe** [comment]
Just checking in to see if I can help - I wasn't involved in this indicator so am unassigning myself. Feel free to re-assign me of course if you feel you can guide me as to what to do. 😄

**Comment by blakeelias** [comment]
Hey @CMorenoStokoe  -- sorry for that -- I just wanted to make sure people got the update, and since you've been involved with frontend in general, I thought you might know something about what was happening here. But I guess @felix19350 did more of the work here and would know best?

**Comment by CMorenoStokoe** [comment]
No need to apologise thanks for keeping me up to date- glad Yaneer is almost happy!

On 16 Dec 2020 18:38, Blake Elias <notifications@github.com> wrote:

Hey @CMorenoStokoe<https://github.com/CMorenoStokoe> -- sorry for that -- I just wanted to make sure people got the update, and since you've been involved with frontend in general, I thought you might know something about what was happening here. But I guess @felix19350<https://github.com/felix19350> did more of the work here and would know best?
