### ISSUE TITLE
Button naming

### ISSUE THREAD

**Issue by blakeelias** [Pandemic-Game/pandemic-game#53]
Active label / Un-active label -- add to PlayerAction

Business: Close / Open
Masks: Enforce / Not Enforced

Corresponding color /  display choice
Dark shading for active, etc.
Show difference between default & active

**Comment by blakeelias** [comment]
Names of the policy on the left side

**Comment by CMorenoStokoe** [comment]
Due to weird on-select behavior I decided NOT to color buttons grey - the shading meant that it wasn't clear whether buttons were on/off. With color, the weird shading was not as big a problem. See pic below: You can see it is grey but it is definitely NOT green. 

I recommend that this issue should be fixed before removing colors.

![image](https://user-images.githubusercontent.com/48444574/101292517-d7b7b700-3807-11eb-9a5b-8c27cbb32700.png)

**Comment by CMorenoStokoe** [comment]
I am leaving this open because the second requirement (color) was not addressed, while the first (naming) was.

**Comment by CMorenoStokoe** [comment]
### Summary

_Addressed issues_
- Active/inactive labels added to replace icons
- Grey has big issues outlined above so green **NOT** removed from active buttons

_New issues_
- The source of the dark grey styling on selected buttons should be identified and removed to reduce confusion

**Comment by CMorenoStokoe** [comment]
Closing with summary above, opening new issue for dark grey ^
